### ISSUE TITLE
Save Kepler data in CARTO

### ISSUE THREAD

**Issue by alasarr** [CartoDB/kepler.gl#1] opened 2019-08-07 07:54 UTC
The main goal of this issue is to save a Kepler map in CARTO. We could include a Save at CARTO `button` at the UI.

This button will show a form to type the title and the description.

If OAuth gives us headaches, let's introduce in that form the `username` and the `master api key`. We will figure out how to accomplish it with OAuth.

First step: we need to take all the datasets defined in the map and load it into CARTO using the import API. 

Second step: create a table `kepler_viz`to store the map config of Kepler and save there Kepler's map config. 

Need to deal with the creation of table `kepler_viz`and to avoid to duplicate dataset if the user clicks on save multiple times.

**Comment by rjimenezda** [comment] 2019-08-07 23:20
Some nightly progress updates, not exactly amazing news.

The import API is **not CORS enabled**, so we either enable it or go back to the Copy plan. When the browser sends an OPTION request to the API, it just spits out 404.

The COPY endpoint works with CORS[1], but I can't set transfer-encoding to `chunked`, apparently that's not allowed. I'll ask backend people what this might mean limits wise. I guess that massive datasets could fail? The timeout is allegedly several hours so I still think it should be fine. Maybe the browser will chunk it anyway, I have to test a really big dataset instead of just small tests. In any case, not a PoC issue imho.

Since the import API path is completely closed right now, I've looked more into the copy path. 

There are two main pains when dealing with the copy api:

1. You have to create the table by hand and cartodbify it.
2. You need the dataset itself formatted as CSV.

Regarding 1:
We have a list of fields and their type, courtesy of kepler, so dynamically building the table is not as bad as I thought. We have to do some trial and error to match their types to postgres types, but that's just a matter of fine tuning and controlling the demo data.

Regarding 2:
Luckliy for us, kepler generates pretty much only CSV files to export data. The issue is, what happens with geometry columns?

From what I've gathered, if it's a CARTO dataset loaded with geojson, you can get the original geometry back. There's always a `_geojson` column that contains the original geojson, so it's just a matter of parsing and discarding it when generating the CSV to send to the copy api (somehow).

However, if you import some kepler-supported CSV, like their examples, things get gnarlier. They support multi geometry tables. So you can have several geometries per per row, and you just get a layer for each one of them. Even when there's only one geometry per feature, you still don't get it nicely parsed, you just get the columns raw values. There's no clear: this feature's geometry is a Point (x, y), you'd have to go through each column and figure out which one (or which pairs) look like geometry.

What I'd suggest at this point is to try to save geojson datasets with a decent the_geom column, but if it's a CSV from whatever random source, leave its the_geom empty, and importing their columns as they are. Hopefully that means that it will 'just work' when reimporting them into kepler, and that you can geocode them in CARTO if you want to use them in our platform.

BTW, having the import API CORS enabled would just mean we don't have to do so much logic, but it takes much longer and is asynchronous, so there's still extra work to do (status polling). Also, I'm sure there's a good reason why it's not, or maybe I'm just the first one doing it from the browser.

cc @VictorVelarde @jesusbotella just so you're up to speed.

[1] You cannot specify the content type of the Blob, though.

**Comment by rjimenezda** [comment] 2019-08-08 11:47
I've succesfully imported CARTO datasets and some of the CSV they have as examples using COPY. I'm having some issues with geometries that are not points because of formatting, but it's looking good :+1: 

Saving the map itself it easier, it's just writing to a table.

I'll deploy it as soon as I have a decent UI state and solve the geometry issues

**Comment by alasarr** [comment] 2019-08-08 13:55
Regarding CORS, you're right I've just remembered when I did something similar from the browser I had to create a proxy to bypass the CORS. We have an [open ticket for this ](https://github.com/CartoDB/cartodb/issues/2546#issuecomment-220559464)

**Comment by alasarr** [comment] 2019-08-08 14:44
According to that point:

>Luckliy for us, kepler generates pretty much only CSV files to export data. The issue is, what happens with geometry columns?

If you export from Kepler in JSON it brings the data back in json format. 

My suggestion is to store this data as it's in CARTO, just transforming the Kepler's types to Postgresql's types. 

That's the first step because it will accomplish the first goal: "use CARTO as data storage for Kepler". 

After that, we can work with the second step, making the datasets available at CARTO, work on the cartodbify.

**Comment by alasarr** [comment] 2019-08-08 14:46
I mean I prefer to have the limitation on datasets which could not be rendered at CARTO but not limited the functionality between CARTO and Kepler

**Comment by rjimenezda** [comment] 2019-08-08 17:35
I got the map saving working too. Tomorrow I'll:

- Polish the UI for the map saving, there's only feedback for dataset uploading.
- Deploy this on GH pages

Move on to the next step which would be loading data back from carto into kepler :muscle: 

I haven't been able to change the privacy through the SQL api, that's done in metadata, so I think we'll need the OAuth read all datasets or keep working with the master key.

**Comment by VictorVelarde** [comment] 2019-08-09 08:35
If master key works fine, I would go that path. Any other OAuth change is probably going to take more time than we have now.

**Comment by alasarr** [comment] 2019-08-13 07:33
Hi @rjimenezda, I've just run the demo at it looks great! 😄 

A couple of issues I've seen, I think could be good to change:

- [ ] Rename `Export to CARTO` to `Save at CARTO`
- [ ] It looks for a new account you need to create the table `kepler_gl_maps`. Could we do it automatically? In the meantime, could you provide me the CREATE TABLE command to create this table?

**Comment by rjimenezda** [comment] 2019-08-13 08:02
Will rename it.

About that second point, what I'm doing is just running a `create table if not exists kepler_gl_maps`, it should work for new accounts, but I'll try in mine

**Comment by alasarr** [comment] 2019-08-13 10:03
>About that second point, what I'm doing is just running a create table if not exists kepler_gl_maps, it should work for new accounts, but I'll try in mine

Let me know when this is ready and I can check this out from my account

**Comment by rjimenezda** [comment] 2019-08-13 10:29
That's already there, any query that is going to fetch stuff from kepler_gl_data does a `create table if not exists` before

**Comment by alasarr** [comment] 2019-08-13 11:53
Working now! I don't know why it complained saying  `kepler_gl_data relation doesn't exist` but not happening anymore...

**Comment by rjimenezda** [comment] 2019-08-13 14:38
My bad, there was one case in which it didn't (when checking if the map name exists already)

**Comment by VictorVelarde** [comment] 2019-09-16 20:18
I'm closing this one, as we have restructured the work for the current cycle

**Closed as completed by VictorVelarde** 2019-09-16 20:18 UTC
